/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-22 04:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.example.jstl.*;
import java.util.ArrayList;

public final class E_005fHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.example.jstl");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    E_User auth = (E_User) session.getAttribute("auth"); // Retrieve "auth" from request attribute, not session

    if(auth != null){
        request.setAttribute("auth", auth);
    }

    E_ProductDao pd = new E_ProductDao(Conn.getConnection());
    List<E_Product> products = pd.getAllProducts();

    ArrayList<E_Cart> cart_list = (ArrayList<E_Cart>) session.getAttribute("cart-list");

    if(cart_list!=null){
        request.setAttribute("cart_list",cart_list);
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Stars Collections</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"description\" content=\"Colo Shop Template\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/bootstrap4/bootstrap.min.css\">\r\n");
      out.write("    <link href=\"CSS/plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/plugins/OwlCarousel2-2.2.1/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/E_Home.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"super_container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("\r\n");
      out.write("    <header class=\"header trans_300\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Top Navigation -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"top_nav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"top_nav_left\">free shipping on all u.s orders over $50</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 text-right\">\r\n");
      out.write("                        <div class=\"top_nav_right\">\r\n");
      out.write("                            <ul class=\"top_nav_menu\">\r\n");
      out.write("\r\n");
      out.write("                                <!-- Currency / Language / My Account -->\r\n");
      out.write("\r\n");
      out.write("                                <li class=\"currency\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        usd\r\n");
      out.write("                                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"currency_selection\">\r\n");
      out.write("                                        <li><a href=\"#\">cad</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">aud</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">eur</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">gbp</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"language\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        English\r\n");
      out.write("                                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"language_selection\">\r\n");
      out.write("                                        <li><a href=\"#\">Hindi</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">English</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Tamil</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Marathi</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"account\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        My Account\r\n");
      out.write("                                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"account_selection\">\r\n");
      out.write("                                        ");
 if(auth!=null) { 
      out.write("\r\n");
      out.write("                                           <li><a href=\"E_Logout-servlet\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i>LogOut</a></li>\r\n");
      out.write("                                        ");
 }else { 
      out.write("\r\n");
      out.write("                                            <li><a href=\"E_Form.jsp\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>Register/Login</a></li>\r\n");
      out.write("                                        ");
}
      out.write("\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Navigation -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main_nav_container\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12 text-right\">\r\n");
      out.write("                        <div class=\"logo_container\">\r\n");
      out.write("                            <a href=\"#\">Anime<span>Store</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <nav class=\"navbar\">\r\n");
      out.write("                            <ul class=\"navbar_menu\">\r\n");
      out.write("                                <li><a href=\"E_Home.jsp\">home</a></li>\r\n");
      out.write("                                <li><a href=\"#shops\">shop</a></li>\r\n");
      out.write("                                <li><a href=\"#blogs\">blog</a></li>\r\n");
      out.write("                                <li><a href=\"#contact\">contact</a></li>\r\n");
      out.write("                                ");
 if (auth != null) { 
      out.write("\r\n");
      out.write("                                <li><a href=\"E_Order.jsp\">Orders</a></li>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"navbar_user\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                                <li class=\"checkout\">\r\n");
      out.write("                                    <a href=\"E_Cart.jsp\">\r\n");
      out.write("                                        <i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <span id=\"checkout_items\" class=\"checkout_items\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart_list.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"hamburger_container\">\r\n");
      out.write("                                <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fs_menu_overlay\"></div>\r\n");
      out.write("    <div class=\"hamburger_menu\">\r\n");
      out.write("        <div class=\"hamburger_close\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("        <div class=\"hamburger_menu_content text-right\">\r\n");
      out.write("            <ul class=\"menu_top_nav\">\r\n");
      out.write("                <li class=\"menu_item has-children\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        usd\r\n");
      out.write("                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"menu_selection\">\r\n");
      out.write("                        <li><a href=\"#\">cad</a></li>\r\n");
      out.write("                        <li><a href=\"#\">aud</a></li>\r\n");
      out.write("                        <li><a href=\"#\">eur</a></li>\r\n");
      out.write("                        <li><a href=\"#\">gbp</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu_item has-children\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        English\r\n");
      out.write("                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"menu_selection\">\r\n");
      out.write("                        <li><a href=\"#\">French</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Italian</a></li>\r\n");
      out.write("                        <li><a href=\"#\">German</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Spanish</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu_item has-children\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        My Account\r\n");
      out.write("                        <i class=\"fa fa-angle-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"menu_selection\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i>Sign In</a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>Register</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#\">home</a></li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#\">shop</a></li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#\">promotion</a></li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#\">pages</a></li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#\">blog</a></li>\r\n");
      out.write("                <li class=\"menu_item\"><a href=\"#contact\">contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slider -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main_slider\" style=\"background-image:url(Images/g2.gif); opacity: 0.7\">\r\n");
      out.write("        <div class=\"container fill_height\">\r\n");
      out.write("            <div class=\"row align-items-center fill_height\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"main_slider_content\" style=\"\">\r\n");
      out.write("                        <h6 style=\"color: white\">Spring / Summer Collection 2024</h6>\r\n");
      out.write("                        <h1 style=\"color: white\">>Get up to 30% Off New Arrivals</h1>\r\n");
      out.write("                        <div class=\"red_button shop_now_button\"><a href=\"#\">shop now</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"banner\" style=\"margin-top: 18%\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"banner_item align-items-center\" style=\"background-image:url(Images/p1.jpg)\">\r\n");
      out.write("                        <div class=\"banner_category\">\r\n");
      out.write("                            <a href=\"#\">women's</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"banner_item align-items-center\" style=\"background-image:url(Images/w1.webp)\">\r\n");
      out.write("                        <div class=\"banner_category\">\r\n");
      out.write("                            <a href=\"#\">accessories's</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"banner_item align-items-center\" style=\"background-image:url(Images/v3-removebg-preview.png)\">\r\n");
      out.write("                        <div class=\"banner_category\">\r\n");
      out.write("                            <a href=\"#\">men's</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div >\r\n");
      out.write("\r\n");
      out.write("    <!-- New Arrivals -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"new_arrivals\" id=\"shops\" style=\"margin-top: 15%\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col text-center\">\r\n");
      out.write("                    <div class=\"section_title new_arrivals_title\">\r\n");
      out.write("                        <h2>New Collection's</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col text-center\">\r\n");
      out.write("                    <div class=\"new_arrivals_sorting\">\r\n");
      out.write("                        <ul class=\"arrivals_grid_sorting clearfix button-group filters-button-group\">\r\n");
      out.write("                            <li class=\"grid_sorting_button button d-flex flex-column justify-content-center align-items-center active is-checked\" data-filter=\"*\">all</li>\r\n");
      out.write("                            <li class=\"grid_sorting_button button d-flex flex-column justify-content-center align-items-center\" data-filter=\".women\">women's</li>\r\n");
      out.write("                            <li class=\"grid_sorting_button button d-flex flex-column justify-content-center align-items-center\" data-filter=\".accessories\">accessories</li>\r\n");
      out.write("                            <li class=\"grid_sorting_button button d-flex flex-column justify-content-center align-items-center\" data-filter=\".men\">men's</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"product-grid\" data-isotope='{ \"itemSelector\": \".product-item\", \"layoutMode\": \"fitRows\" }'>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Product 1 -->\r\n");
      out.write("                        ");

                            if(!products.isEmpty()){
                                for(E_Product product : products){
      out.write("\r\n");
      out.write("                                    <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                        <div class=\"product discount product_filter\">\r\n");
      out.write("                                            <div class=\"product_image\">\r\n");
      out.write("                                                <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                            <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                            <div class=\"product_info\">\r\n");
      out.write("                                                <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                                <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                        <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                ");
}
                            }
                        
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Deal of the week -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"deal_ofthe_week\" style=\"margin-top: 5%\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"deal_ofthe_week_img\">\r\n");
      out.write("                        <img src=\"./Images/l1-Photoroom.png-Photoroom.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-6 text-right deal_ofthe_week_col\">\r\n");
      out.write("                    <div class=\"deal_ofthe_week_content d-flex flex-column align-items-center float-right\">\r\n");
      out.write("                        <div class=\"section_title\">\r\n");
      out.write("                            <h2>Deal Of The Week</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"timer\">\r\n");
      out.write("                            <li class=\"d-inline-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                <div id=\"day\" class=\"timer_num\">03</div>\r\n");
      out.write("                                <div class=\"timer_unit\">Day</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"d-inline-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                <div id=\"hour\" class=\"timer_num\">15</div>\r\n");
      out.write("                                <div class=\"timer_unit\">Hours</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"d-inline-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                <div id=\"minute\" class=\"timer_num\">45</div>\r\n");
      out.write("                                <div class=\"timer_unit\">Mins</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"d-inline-flex flex-column justify-content-center align-items-center\">\r\n");
      out.write("                                <div id=\"second\" class=\"timer_num\">23</div>\r\n");
      out.write("                                <div class=\"timer_unit\">Sec</div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"red_button deal_ofthe_week_button\"><a href=\"#\">shop now</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Best Sellers -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"best_sellers\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col text-center\">\r\n");
      out.write("                    <div class=\"section_title new_arrivals_title\">\r\n");
      out.write("                        <h2>Best Sellers</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"product_slider_container\">\r\n");
      out.write("                        <div class=\"owl-carousel owl-theme product_slider\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 1 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 2 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 3 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 4 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 5 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 6 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 7 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                ");

                                    if(!products.isEmpty()){
                                        for(E_Product product : products){
      out.write("\r\n");
      out.write("                                <div class=\"product-item ");
      out.print(product.getCategory());
      out.write("\" style=\"margin-top: 5%;margin-left: 5%\">\r\n");
      out.write("                                    <div class=\"product discount product_filter\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/");
      out.print(product.getImage());
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>-$20</span></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"E_Single.jsp\">");
      out.print( product.getName());
      out.write("</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">");
      out.print( product.getPrice());
      out.write("<span>$590.00</span></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"Add_E_Cart-servlet?id=");
      out.print( product.getId());
      out.write("\">add to cart</a></div>\r\n");
      out.write("                                    <div class=\"red_button add_to_cart_button\"><a href=\"E_Oder-servlet?quantity=1\"");
      out.print( product.getId());
      out.write("\">Buy Now</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
}
                                }
                                
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 8 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                <div class=\"product-item men\">\r\n");
      out.write("                                    <div class=\"product\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/a7.webp\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center\"><span>sale</span></div>\r\n");
      out.write("                                        <div class=\"favorite favorite_left\"></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"#\">DYMO LabelWriter 450 Turbo Thermal Label Printer</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">$410.00</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Slide 10 -->\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"owl-item product_slider_item\">\r\n");
      out.write("                                <div class=\"product-item men\">\r\n");
      out.write("                                    <div class=\"product\">\r\n");
      out.write("                                        <div class=\"product_image\">\r\n");
      out.write("                                            <img src=\"./Images/a3.webp\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"favorite\"></div>\r\n");
      out.write("                                        <div class=\"product_info\">\r\n");
      out.write("                                            <h6 class=\"product_name\"><a href=\"#\">Pryma Headphones, Rose Gold & Grey</a></h6>\r\n");
      out.write("                                            <div class=\"product_price\">$180.00</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Slider Navigation -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"product_slider_nav_left product_slider_nav d-flex align-items-center justify-content-center flex-column\">\r\n");
      out.write("                            <i class=\"fa fa-chevron-left\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product_slider_nav_right product_slider_nav d-flex align-items-center justify-content-center flex-column\">\r\n");
      out.write("                            <i class=\"fa fa-chevron-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Benefit -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"benefit\" style=\"margin-top: 10%;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row benefit_row\">\r\n");
      out.write("                <div class=\"col-lg-3 benefit_col\">\r\n");
      out.write("                    <div class=\"benefit_item d-flex flex-row align-items-center\">\r\n");
      out.write("                        <div class=\"benefit_icon\"><i class=\"fa fa-truck\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("                        <div class=\"benefit_content\">\r\n");
      out.write("                            <h6>free shipping</h6>\r\n");
      out.write("                            <p>Suffered Alteration in Some Form</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 benefit_col\">\r\n");
      out.write("                    <div class=\"benefit_item d-flex flex-row align-items-center\">\r\n");
      out.write("                        <div class=\"benefit_icon\"><i class=\"fa fa-money\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("                        <div class=\"benefit_content\">\r\n");
      out.write("                            <h6>cach on delivery</h6>\r\n");
      out.write("                            <p>The Internet Tend To Repeat</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 benefit_col\">\r\n");
      out.write("                    <div class=\"benefit_item d-flex flex-row align-items-center\">\r\n");
      out.write("                        <div class=\"benefit_icon\"><i class=\"fa fa-undo\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("                        <div class=\"benefit_content\">\r\n");
      out.write("                            <h6>45 days return</h6>\r\n");
      out.write("                            <p>Making it Look Like Readable</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 benefit_col\"  id=\"blogs\" >\r\n");
      out.write("                    <div class=\"benefit_item d-flex flex-row align-items-center\">\r\n");
      out.write("                        <div class=\"benefit_icon\"><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i></div>\r\n");
      out.write("                        <div class=\"benefit_content\">\r\n");
      out.write("                            <h6>opening all week</h6>\r\n");
      out.write("                            <p>8AM - 09PM</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Blogs -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"blogs\" style=\"margin-top:5%\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col text-center\">\r\n");
      out.write("                    <div class=\"section_title\">\r\n");
      out.write("                        <h2>Latest Blogs</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row blogs_container\" style=\"margin-top:10%;margin-bottom: 20%\">\r\n");
      out.write("                <div class=\"col-lg-4 blog_item_col\">\r\n");
      out.write("                    <div class=\"blog_item\">\r\n");
      out.write("                        <div class=\"blog_background\" style=\"background-image:url(Images/o1.jpeg)\"></div>\r\n");
      out.write("                        <div class=\"blog_content d-flex flex-column align-items-center justify-content-center text-center\">\r\n");
      out.write("                            <h4 class=\"blog_title\">Here are the trends I see coming this fall</h4>\r\n");
      out.write("                            <span class=\"blog_meta\">by admin | dec 01, 2024</span>\r\n");
      out.write("                            <a class=\"blog_more\" href=\"#\">Read more</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 blog_item_col\">\r\n");
      out.write("                    <div class=\"blog_item\">\r\n");
      out.write("                        <div class=\"blog_background\" style=\"background-image:url(Images/o2.jpeg)\"></div>\r\n");
      out.write("                        <div class=\"blog_content d-flex flex-column align-items-center justify-content-center text-center\">\r\n");
      out.write("                            <h4 class=\"blog_title\">Here are the trends I see coming this fall</h4>\r\n");
      out.write("                            <span class=\"blog_meta\">by admin | dec 01, 2024</span>\r\n");
      out.write("                            <a class=\"blog_more\" href=\"#\">Read more</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 blog_item_col\">\r\n");
      out.write("                    <div class=\"blog_item\">\r\n");
      out.write("                        <div class=\"blog_background\" style=\"background-image:url(Images/2.webp)\"></div>\r\n");
      out.write("                        <div class=\"blog_content d-flex flex-column align-items-center justify-content-center text-center\">\r\n");
      out.write("                            <h4 class=\"blog_title\">Here are the trends I see coming this fall</h4>\r\n");
      out.write("                            <span class=\"blog_meta\">by admin | dec 01, 2024</span>\r\n");
      out.write("                            <a class=\"blog_more\" href=\"#\">Read more</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Newsletter -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"newsletter\" id=\"contact\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center\">\r\n");
      out.write("                        <h4>Newsletter</h4>\r\n");
      out.write("                        <p>Subscribe to our newsletter and get 20% off your first purchase</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <form action=\"post\">\r\n");
      out.write("                        <div class=\"newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center\">\r\n");
      out.write("                            <input id=\"newsletter_email\" type=\"email\" placeholder=\"Your email\" required=\"required\" data-error=\"Valid email is required.\">\r\n");
      out.write("                            <button id=\"newsletter_submit\" type=\"submit\" class=\"newsletter_submit_btn trans_300\" value=\"Submit\">subscribe</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center\">\r\n");
      out.write("                        <ul class=\"footer_nav\">\r\n");
      out.write("                            <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                            <li><a href=\"#\">FAQs</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-skype\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"footer_nav_container\">\r\n");
      out.write("                        <div class=\"cr\">©2018 All Rights Reserverd. Made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"#\">itzrahul2002</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"JS/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"CSS/bootstrap4/popper.js\"></script>\r\n");
      out.write("<script src=\"CSS/bootstrap4/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"CSS/plugins/Isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"CSS/plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"CSS/plugins/easing/easing.js\"></script>\r\n");
      out.write("<script src=\"JS/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
